In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/Mtrl Selection using ML.csv")

In [4]:
df.head()

,Std,ID,Material,Heat treatment,Su,Sy,A5,Bhn,E,G,mu,Ro,pH,Desc,HV
0,ANSI,D8894772B88F495093C43AF905AB6373,Steel SAE 1015,as-rolled,421,314,39.0,126.0,207000,79000,0.3,7860,NaN,NaN,NaN
1,ANSI,05982AC66F064F9EBC709E7A4164613A,Steel SAE 1015,normalized,424,324,37.0,121.0,207000,79000,0.3,7860,NaN,NaN,NaN
2,ANSI,356D6E63FF9A49A3AB23BF66BAC85DC3,Steel SAE 1015,annealed,386,284,37.0,111.0,207000,79000,0.3,7860,NaN,NaN,NaN
3,ANSI,1C758F8714AC4E0D9BD8D8AE1625AECD,Steel SAE 1020,as-rolled,448,331,36.0,143.0,207000,79000,0.3,7860,NaN,NaN,NaN
4,ANSI,DCE10036FC1946FC8C9108D598D116AD,Steel SAE 1020,normalized,441,346,35.8,131.0,207000,79000,0.3,7860,550.0,NaN,NaN

In [5]:
df.head(10)

,Std,ID,Material,Heat treatment,Su,Sy,A5,Bhn,E,G,mu,Ro,pH,Desc,HV
0,ANSI,D8894772B88F495093C43AF905AB6373,Steel SAE 1015,as-rolled,421,314,39.0,126.0,207000,79000,0.3,7860,NaN,NaN,NaN
1,ANSI,05982AC66F064F9EBC709E7A4164613A,Steel SAE 1015,normalized,424,324,37.0,121.0,207000,79000,0.3,7860,NaN,NaN,NaN
2,ANSI,356D6E63FF9A49A3AB23BF66BAC85DC3,Steel SAE 1015,annealed,386,284,37.0,111.0,207000,79000,0.3,7860,NaN,NaN,NaN
3,ANSI,1C758F8714AC4E0D9BD8D8AE1625AECD,Steel SAE 1020,as-rolled,448,331,36.0,143.0,207000,79000,0.3,7860,NaN,NaN,NaN
4,ANSI,DCE10036FC1946FC8C9108D598D116AD,Steel SAE 1020,normalized,441,346,35.8,131.0,207000,79000,0.3,7860,550.0,NaN,NaN
5,ANSI,2EC038241908434FA714FEEBE24DDEFE,Steel SAE 1020,annealed,395,295,36.5,111.0,207000,79000,0.3,7860,NaN,NaN,NaN
6,ANSI,356B183DD9E34A1C80A5028D43B9E149,Steel SAE 1022,as-rolled,503,359,35.0,149.0,207000,79000,0.3,7860,NaN,NaN,NaN
7,ANSI,95CB82FA86314D8490932A9E740744E3,Steel SAE 1022,normalized,483,359,34.0,143.0,207000,79000,0.3,7860,NaN,NaN,NaN
8,ANSI,942333E2D11B4C2CA0B9DFD6D1CE38E0,Steel SAE 1022,annealed,450,317,35.0,137.0,207000,79000,0.3,7860,NaN,NaN,NaN
9,ANSI,5E035DD0692F47E3A92EB298101AA124,Steel SAE 1030,as-rolled,552,345,32.0,179.0,207000,79000,0.3,7860,NaN,NaN,NaN

In [6]:
df.tail()

,Std,ID,Material,Heat treatment,Su,Sy,A5,Bhn,E,G,mu,Ro,pH,Desc,HV
1547,JIS,512A80EC21EA416BA2725B38BA8096EF,Nodular cast iron,NaN,600,370,NaN,NaN,169000,70000,0.20,7160,480.0,Nodular cast iron,210.0
1548,JIS,38526441BA8741CA979DBF870D0B8A9B,Nodular cast iron,NaN,700,420,NaN,NaN,169000,70000,0.20,7160,560.0,Nodular cast iron,230.0
1549,JIS,CAC03D7EB1AA45E68EFF92A2EF4C3D9B,Nodular cast iron,NaN,800,480,NaN,NaN,169000,70000,0.20,7160,600.0,Nodular cast iron,240.0
1550,JIS,45C82A36EC644F8BB6170A99ED819B62,Malleable cast iron,NaN,400,180,4.0,NaN,160000,64000,0.27,7160,300.0,Malleable cast iron,220.0
1551,JIS,BC74F870412F4DDBADDEF1063C1C079F,Malleable cast iron,NaN,500,260,4.0,NaN,160000,64000,0.27,7160,370.0,Malleable cast iron,230.0

In [7]:
df.tail(10)

,Std,ID,Material,Heat treatment,Su,Sy,A5,Bhn,E,G,mu,Ro,pH,Desc,HV
1542,JIS,C56510CA1A514586B57FA1DEDEF9381F,Grey cast iron,NaN,200,200,NaN,NaN,85000,34000,0.25,7160,340.0,Grey cast iron,210.0
1543,JIS,E954C28700D9457484FBE1A6EC3F7C08,Grey cast iron,NaN,250,250,NaN,NaN,85000,34000,0.25,7160,400.0,Grey cast iron,230.0
1544,JIS,5F3EA6C8EE4F4129A1C3D20B8AF50999,Grey cast iron,NaN,300,300,NaN,NaN,85000,34000,0.25,7160,460.0,Grey cast iron,250.0
1545,JIS,48002D4F94F84AC9B4820173CB6B720B,Grey cast iron,NaN,350,350,NaN,NaN,85000,34000,0.25,7160,520.0,Grey cast iron,260.0
1546,JIS,FF34D361E5F340F2A9E6595868F01D7B,Nodular cast iron,NaN,500,320,NaN,NaN,169000,70000,0.20,7160,400.0,Nodular cast iron,180.0
1547,JIS,512A80EC21EA416BA2725B38BA8096EF,Nodular cast iron,NaN,600,370,NaN,NaN,169000,70000,0.20,7160,480.0,Nodular cast iron,210.0
1548,JIS,38526441BA8741CA979DBF870D0B8A9B,Nodular cast iron,NaN,700,420,NaN,NaN,169000,70000,0.20,7160,560.0,Nodular cast iron,230.0
1549,JIS,CAC03D7EB1AA45E68EFF92A2EF4C3D9B,Nodular cast iron,NaN,800,480,NaN,NaN,169000,70000,0.20,7160,600.0,Nodular cast iron,240.0
1550,JIS,45C82A36EC644F8BB6170A99ED819B62,Malleable cast iron,NaN,400,180,4.0,NaN,160000,64000,0.27,7160,300.0,Malleable cast iron,220.0
1551,JIS,BC74F870412F4DDBADDEF1063C1C079F,Malleable cast iron,NaN,500,260,4.0,NaN,160000,64000,0.27,7160,370.0,Malleable cast iron,230.0

In [8]:
df.shape

(1552, 15)

In [9]:
df.describe()

,Su,A5,Bhn,E,G,mu,Ro,pH,HV
count,1552.000000,1346.000000,463.000000,1552.000000,1552.000000,1552.000000,1552.000000,193.000000,165.000000
mean,572.753222,19.329421,177.138229,164571.520619,85598.840206,0.302977,6929.843428,627.393782,328.484848
std,326.834927,12.422004,113.508044,56135.405867,125326.800138,0.024590,2115.171710,370.530293,202.764089
min,69.000000,0.500000,19.000000,73000.000000,26000.000000,0.200000,1750.000000,190.000000,105.000000
25%,340.000000,11.000000,78.000000,105000.000000,40000.000000,0.300000,7160.000000,370.000000,192.000000
50%,500.000000,16.000000,170.000000,206000.000000,79000.000000,0.300000,7860.000000,460.000000,230.000000
75%,705.000000,24.375000,229.000000,206000.000000,80000.000000,0.320000,7860.000000,796.000000,492.000000
max,2220.000000,70.000000,627.000000,219000.000000,769000.000000,0.350000,8930.000000,1360.000000,800.000000

In [10]:
df.isnull().sum()

Std                  0
ID                   0
Material             0
Heat treatment     750
Su                   0
Sy                   0
A5                 206
Bhn               1089
E                    0
G                    0
mu                   0
Ro                   0
pH                1359
Desc               571
HV                1387
dtype: int64