In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/Restaurant_3.csv")

In [4]:
df.head()

,DATE,TIME,INVOICE_NO,ITEM,QUANTITY,RATE,SUB_TOTAL,AMOUNT,DAY,CATEGORY,PERSON
0,01-10-2023,12.08,3,CHAPPATHI,3,18,54,54.0,1_,MAIN DISH,1.0
1,01-10-2023,12.15,4,CHILLI CHICKEN,1,100,100,320.0,1_,STARTER,2.0
2,01-10-2023,12.15,4,CHICKEN BIRIYANI,2,110,220,NaN,1_,MAIN DISH,NaN
3,01-10-2023,12.15,5,PAROTTA,2,18,36,36.0,1_,MAIN DISH,1.0
4,01-10-2023,12.36,7,KALAKI,1,15,15,69.0,1_,STARTER,1.0

In [5]:
df.head(10)

,DATE,TIME,INVOICE_NO,ITEM,QUANTITY,RATE,SUB_TOTAL,AMOUNT,DAY,CATEGORY,PERSON
0,01-10-2023,12.08,3,CHAPPATHI,3,18,54,54.0,1_,MAIN DISH,1.0
1,01-10-2023,12.15,4,CHILLI CHICKEN,1,100,100,320.0,1_,STARTER,2.0
2,01-10-2023,12.15,4,CHICKEN BIRIYANI,2,110,220,NaN,1_,MAIN DISH,NaN
3,01-10-2023,12.15,5,PAROTTA,2,18,36,36.0,1_,MAIN DISH,1.0
4,01-10-2023,12.36,7,KALAKI,1,15,15,69.0,1_,STARTER,1.0
5,01-10-2023,12.36,7,PAROTTA,3,18,54,NaN,1_,MAIN DISH,NaN
6,01-10-2023,12.50,9,CHICKEN BIRIYANI,1,110,110,110.0,1_,MAIN DISH,1.0
7,01-10-2023,13.01,10,PAROTTA,2,18,36,36.0,1_,MAIN DISH,1.0
8,01-10-2023,13.03,11,EGG MASALA,1,70,70,160.0,1_,GRAVY,2.0
9,01-10-2023,13.03,11,PAROTTA,5,18,90,NaN,1_,MAIN DISH,NaN

In [6]:
df.tail()

,DATE,TIME,INVOICE_NO,ITEM,QUANTITY,RATE,SUB_TOTAL,AMOUNT,DAY,CATEGORY,PERSON
608,02-10-2023,22.12,9159,GOLI SODA,3,30,90,728.0,2_,BEVRAGE,NaN
609,02-10-2023,22.12,9159,GHEE PODI ROAST,1,60,60,NaN,2_,MAIN DISH,NaN
610,02-10-2023,22.12,9159,CHICKEN PALLIPALAYAM,1,120,120,NaN,2_,GRAVY,NaN
611,02-10-2023,22.12,9159,PEPPER CHICKEN MASALA,1,130,130,NaN,2_,GRAVY,NaN
612,02-10-2023,22.12,9159,MUSHROOM CHILLI,1,80,80,NaN,2_,STARTER,NaN

In [7]:
df.tail(10)

,DATE,TIME,INVOICE_NO,ITEM,QUANTITY,RATE,SUB_TOTAL,AMOUNT,DAY,CATEGORY,PERSON
603,02-10-2023,22.06,9155,CHICKEN NOODLES,1,100,100,NaN,2_,MAIN DISH,NaN
604,02-10-2023,22.06,9155,CHICKEN PAROTTA,1,90,90,665.0,2_,MAIN DISH,NaN
605,02-10-2023,22.06,9155,GILMA BIRIYANI,1,130,130,NaN,2_,MAIN DISH,NaN
606,02-10-2023,22.12,9159,PAROTTA,6,18,108,NaN,2_,MAIN DISH,3.0
607,02-10-2023,22.12,9159,CHICKEN DOSA,2,70,140,NaN,2_,MAIN DISH,NaN
608,02-10-2023,22.12,9159,GOLI SODA,3,30,90,728.0,2_,BEVRAGE,NaN
609,02-10-2023,22.12,9159,GHEE PODI ROAST,1,60,60,NaN,2_,MAIN DISH,NaN
610,02-10-2023,22.12,9159,CHICKEN PALLIPALAYAM,1,120,120,NaN,2_,GRAVY,NaN
611,02-10-2023,22.12,9159,PEPPER CHICKEN MASALA,1,130,130,NaN,2_,GRAVY,NaN
612,02-10-2023,22.12,9159,MUSHROOM CHILLI,1,80,80,NaN,2_,STARTER,NaN

In [8]:
df.shape

(613, 11)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 613 entries, 0 to 612
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   DATE        613 non-null    object
 1   TIME        613 non-null    float64
 2   INVOICE_NO  613 non-null    int64
 3   ITEM        613 non-null    object
 4   QUANTITY    613 non-null    int64
 5   RATE        613 non-null    int64
 6   SUB_TOTAL   613 non-null    int64
 7   AMOUNT      243 non-null    float64
 8   DAY         613 non-null    object
 9   CATEGORY    606 non-null    object
 10  PERSON      243 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 52.8+ KB

In [10]:
df.describe()

,TIME,INVOICE_NO,QUANTITY,RATE,SUB_TOTAL,AMOUNT,PERSON
count,613.000000,613.000000,613.000000,613.000000,613.000000,243.000000,243.000000
mean,18.219250,686.773246,1.750408,57.918434,77.970636,196.691358,1.901235
std,3.414651,2126.360182,2.189850,46.909974,66.920662,150.282652,1.316817
min,12.080000,1.000000,1.000000,10.000000,10.000000,35.000000,1.000000
25%,15.010000,55.000000,1.000000,18.000000,36.000000,89.500000,1.000000
50%,19.420000,102.000000,1.000000,35.000000,70.000000,151.000000,2.000000
75%,21.270000,154.000000,2.000000,100.000000,100.000000,268.000000,2.000000
max,23.400000,9159.000000,44.000000,530.000000,792.000000,792.000000,15.000000

In [11]:
df.isnull().sum()

DATE            0
TIME            0
INVOICE_NO      0
ITEM            0
QUANTITY        0
RATE            0
SUB_TOTAL       0
AMOUNT        370
DAY             0
CATEGORY        7
PERSON        370
dtype: int64